RESOLUTION = WIDTH, HEIGHT = 1280, 720

BACKGROUND = 'lightblue'
TEXTCOLOR = 'black'

FPS = 60
GRAVITY_CONST = HEIGHT
JETPACK_POWER = 3*HEIGHT

PLAYER_DIMENSION = PLAYER_WIDTH, PLAYER_HEIGHT = 40, 80
COIN_DIMENSION = COIN_WIDTH, COIN_HEIGHT = 32, 32
OBSTACLE_DIMENSION = OBSTACLE_WIDTH, OBSTACLE_HEIGHT = 64, 32

MAX_PAYER_SPEED = HEIGHT
MIN_OBJECT_SPEED = 100
OBJECT_SPEED_INTERVAL = 10
MAX_OBJECT_SPEED = WIDTH

UPPER_BORDER: int = 64
LOWER_BORDER: int = HEIGHT - 64

OBJECT_SPAWN = 1
CLOUD_SPAWN_RATE = 2

FONT = 'Arial'
MUSIC_VOLUME = 0.25

MENU_IDLE = 50

START_WIDTH = WIDTH * 0.1
START_HEIGHT = HEIGHT//2
